### ISSUE TITLE
Missing requirements.txt in py-bottom-up-attention

### ISSUE THREAD

**Issue by dinhanhx** [vladsandulescu/hatefulmemes#10]
[airsplay/py-bottom-up-attention/requirements.txt](https://github.com/airsplay/py-bottom-up-attention/blob/master/requirements.txt) I believe that you are missing this file.

**Comment by vladsandulescu** [comment]
You're right, thanks, I added it now. Feel free to make a pull request if you see other missing things, it's faster for me to fix it this way :)
