### ISSUE TITLE
sorry， but the download file url is not exits. very thanks!

### ISSUE THREAD

**Issue by Huangyajuan-123** [vladsandulescu/hatefulmemes#13]

**Comment by vladsandulescu** [comment]
This works for me: https://drive.google.com/drive/folders/1uPukz8AZIcFOgaajGfeJYuQfl9PMYJU9

**Comment by Huangyajuan-123** [comment]
thanks！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vladsandulescu/hatefulmemes"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月16日(星期四) 下午5:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vladsandulescu/hatefulmemes] sorry， but the download file url is not exits. very thanks! (Issue #13)





 
This works for me: https://drive.google.com/drive/folders/1uPukz8AZIcFOgaajGfeJYuQfl9PMYJU9
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
